{
  "swagger": "2.0",
  "info": {
    "description": "用户中心服务器端API文档(v3.1.0)",
    "version": "3.1.0",
    "title": "用户中心API文档",
    "termsOfService": "http://swagger.io/terms",
    "contact": {
      "name": "API Support",
      "url": "http://www.digitalsee.cn/support",
      "email": "ROOTTeam@digitalsee.cn"
    },
    "license": {
      "name": "Apache License Version 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "host": "192-168-50-17-75uievyndse8.ztna.dingtalk.com",
  "basePath": "/",
  "tags": [
    {
      "name": "AppCategory",
      "description": "App category 管理配置"
    },
    {
      "name": "Application",
      "description": "Application 管理配置"
    },
    {
      "name": "Application Role",
      "description": "应用权限角色管理配置"
    },
    {
      "name": "Application Role Assignment",
      "description": "应用角色分配管理"
    },
    {
      "name": "Audit",
      "description": "同步钉钉审计日志信息"
    },
    {
      "name": "Auditlog",
      "description": "审计日志"
    },
    {
      "name": "Auth Factor",
      "description": "认证因子管理配置"
    },
    {
      "name": "CAS",
      "description": "Cas Authorization Endpoint"
    },
    {
      "name": "Configs",
      "description": "系统配置"
    },
    {
      "name": "ConnectDing",
      "description": "钉钉连接器API"
    },
    {
      "name": "Connector",
      "description": "链接器相关"
    },
    {
      "name": "Data Push",
      "description": "数据推送"
    },
    {
      "name": "DeviceCode",
      "description": "扫码登录"
    },
    {
      "name": "Email",
      "description": "邮件配置"
    },
    {
      "name": "Gateway Application",
      "description": "网关Application 管理配置"
    },
    {
      "name": "INNER",
      "description": "Inner Api"
    },
    {
      "name": "Inner Api",
      "description": "日志收集服务"
    },
    {
      "name": "InnerAppApi",
      "description": "IAM对外不需要鉴权的服务接口"
    },
    {
      "name": "Links",
      "description": "连接器相关"
    },
    {
      "name": "Login",
      "description": "登录相关API"
    },
    {
      "name": "Login Policy",
      "description": "登录策略管理配置"
    },
    {
      "name": "Media",
      "description": "媒体文件管理接口"
    },
    {
      "name": "Message",
      "description": "内部消息管理接口"
    },
    {
      "name": "NCM Redirect Api",
      "description": "转发NCM消息接口的API"
    },
    {
      "name": "OpenApi",
      "description": "IAM对外不需要鉴权的服务接口"
    },
    {
      "name": "Org attribute schema",
      "description": "组织结构属性定义"
    },
    {
      "name": "Organization",
      "description": "组织结构管理"
    },
    {
      "name": "Other Protocol Auth",
      "description": "Other Authorization Endpoint"
    },
    {
      "name": "SAML2",
      "description": "Saml 2 Authorization Endpoint"
    },
    {
      "name": "SCIM API",
      "description": "SCIM相关"
    },
    {
      "name": "SSO",
      "description": "UC SSO"
    },
    {
      "name": "System info",
      "description": "Sys Controller"
    },
    {
      "name": "Templates",
      "description": "消息模版"
    },
    {
      "name": "Tenant",
      "description": "Iam Tenant Controller"
    },
    {
      "name": "ThirdParty Application",
      "description": "第三方Application 管理"
    },
    {
      "name": "Tools",
      "description": "相关工具接口"
    },
    {
      "name": "User",
      "description": "用户管理"
    },
    {
      "name": "User Certificate",
      "description": "用户证书管理"
    },
    {
      "name": "User Conversation",
      "description": "标签群聊管理配置"
    },
    {
      "name": "User Profiles",
      "description": "用户画像配置管理"
    },
    {
      "name": "User Tag",
      "description": "用户标签管理配置"
    },
    {
      "name": "User attribute schema",
      "description": "用户属性定义"
    },
    {
      "name": "UserSelf",
      "description": "用户自服务API"
    },
    {
      "name": "aksk-filter-ex-controller",
      "description": "AKSK Filter Ex Controller"
    },
    {
      "name": "data pull",
      "description": "数据拉取"
    },
    {
      "name": "etl-controller",
      "description": "Etl Controller"
    },
    {
      "name": "health-check-controller",
      "description": "Health Check Controller"
    },
    {
      "name": "jwk-set-publishing-endpoint",
      "description": "JWK Set Publishing Endpoint"
    },
    {
      "name": "ldapserver",
      "description": "ldapserver数据接口"
    },
    {
      "name": "notify-controller",
      "description": "Notify Controller"
    },
    {
      "name": "positions",
      "description": "职位管理配置"
    },
    {
      "name": "saml-endpoint",
      "description": "SAML Endpoint"
    },
    {
      "name": "scim-endpoint",
      "description": "SCIM Endpoint"
    },
    {
      "name": "third-party-account-controller",
      "description": "Third Party Account Controller"
    },
    {
      "name": "third-party-call-back-event-controller",
      "description": "Third Party Call Back Event Controller"
    },
    {
      "name": "we-work-controller",
      "description": "We Work Controller"
    }
  ],
  "paths": {
    "/filter/error/aksk": {
      "get": {
        "tags": ["aksk-filter-ex-controller"],
        "summary": "throwException",
        "operationId": "throwExceptionUsingGET",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "head": {
        "tags": ["aksk-filter-ex-controller"],
        "summary": "throwException",
        "operationId": "throwExceptionUsingHEAD",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["aksk-filter-ex-controller"],
        "summary": "throwException",
        "operationId": "throwExceptionUsingPOST",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": ["aksk-filter-ex-controller"],
        "summary": "throwException",
        "operationId": "throwExceptionUsingPUT",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["aksk-filter-ex-controller"],
        "summary": "throwException",
        "operationId": "throwExceptionUsingDELETE",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "options": {
        "tags": ["aksk-filter-ex-controller"],
        "summary": "throwException",
        "operationId": "throwExceptionUsingOPTIONS",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["aksk-filter-ex-controller"],
        "summary": "throwException",
        "operationId": "throwExceptionUsingPATCH",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/actions": {
      "get": {
        "tags": ["Links"],
        "summary": "查询执行动作列表",
        "description": "查询执行动作列表",
        "operationId": "queryActionsUsingGET",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Links"],
        "summary": "创建执行动作",
        "description": "创建执行动作",
        "operationId": "createActionUsingPOST",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/actions/{id}": {
      "get": {
        "tags": ["Links"],
        "summary": "获取执行动作详情",
        "description": "获取执行动作详情",
        "operationId": "getActionUsingGET",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": ["Links"],
        "summary": "替换修改执行动作",
        "description": "替换修改执行动作",
        "operationId": "replaceActionUsingPUT",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Links"],
        "summary": "删除执行动作",
        "description": "删除执行动作",
        "operationId": "deleteActionUsingDELETE",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/app/category": {
      "get": {
        "tags": ["AppCategory"],
        "summary": "获取应用分类列表",
        "description": "获取应用分类列表",
        "operationId": "getAppCategoryListUsingGET",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["AppCategory"],
        "summary": "新增应用分类",
        "description": "新增应用分类",
        "operationId": "createAppCategoryUsingPOST",
        "security": [
          {
            "uc_auth": ["create:apps"]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": ["AppCategory"],
        "summary": "批量修改应用分类",
        "description": "批量修改应用分类",
        "operationId": "batchReplaceAppCategoryUsingPUT",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/app/category/apps": {
      "post": {
        "tags": ["AppCategory"],
        "summary": "批量将应用添加到分类中",
        "description": "批量将应用添加到分类中",
        "operationId": "addAppLinksUsingPOST",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["AppCategory"],
        "summary": "批量将应用从分类中删除",
        "description": "批量将应用从分类中删除",
        "operationId": "delAppLinksUsingDELETE",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/app/category/apps/{client_id}": {
      "put": {
        "tags": ["AppCategory"],
        "summary": "修改应用全部分类",
        "description": "修改应用全部分类",
        "operationId": "updateAppLinksUsingPUT",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/app/category/{id}": {
      "delete": {
        "tags": ["AppCategory"],
        "summary": "删除应用分类",
        "description": "删除应用分类信息",
        "operationId": "deleteAppCategoryUsingDELETE",
        "security": [
          {
            "uc_auth": ["delete:apps"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["AppCategory"],
        "summary": "修改应用分类信息",
        "description": "修改应用分类信息",
        "operationId": "updateAppCategoryUsingPATCH",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps": {
      "get": {
        "tags": ["Application"],
        "summary": "获取应用的列表",
        "description": "获取应用的列表，可以通过应用状态和应用类型做过滤。",
        "operationId": "searchApp",
        "security": [
          {
            "uc_auth": ["search:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/appstore": {
      "get": {
        "tags": ["Application"],
        "summary": "获取应用市场的列表",
        "description": "获取应用市场的列表，可以通过应用名称和应用类型做过滤。",
        "operationId": "searchAppStore",
        "security": [
          {
            "uc_auth": ["search:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/createOrUpdateAppBaseInfo": {
      "post": {
        "tags": ["Application"],
        "summary": "管理员创建或修改应用(基础信息)",
        "description": "管理员创建或修改应用(基础信息)",
        "operationId": "createOrUpdateAppBaseInfoUsingPOST",
        "security": [
          {
            "uc_auth": ["create:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/loginPolicy/{client_id}": {
      "put": {
        "tags": ["Application"],
        "summary": "设置应用认证策略",
        "description": "设置应用认证策略",
        "operationId": "setLoginPolicyUsingPUT",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/preview/assertion": {
      "post": {
        "tags": ["Application"],
        "summary": "预览SAML断言",
        "description": "预览SAML断言",
        "operationId": "previewAssertionUsingPOST",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/updateSSOInfo/{client_id}": {
      "patch": {
        "tags": ["Application"],
        "summary": "修改单点配置信息",
        "description": "修改单点配置信息",
        "operationId": "updateAppSSOInfoUsingPATCH",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/v2": {
      "get": {
        "tags": ["Application"],
        "summary": "获取应用的列表",
        "description": "获取应用的列表，可以通过应用状态和应用类型做过滤。",
        "operationId": "searchApp_1",
        "security": [
          {
            "uc_auth": ["search:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/v2/{client_id}": {
      "get": {
        "tags": ["Application"],
        "summary": "获取应用详细信息",
        "description": "获取应用详细信息",
        "operationId": "getAppDetails_1",
        "security": [
          {
            "uc_auth": ["read:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}": {
      "get": {
        "tags": ["Application"],
        "summary": "获取应用详细信息",
        "description": "获取应用详细信息",
        "operationId": "getAppDetails",
        "security": [
          {
            "uc_auth": ["read:apps"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Application"],
        "summary": "更新应用的详细信息",
        "description": "更新应用的详细信息",
        "operationId": "updateAppV2UsingPOST",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Application"],
        "summary": "删除应用",
        "description": "删除应用",
        "operationId": "deleteApp",
        "security": [
          {
            "uc_auth": ["delete:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/download_cert": {
      "get": {
        "tags": ["Application"],
        "summary": "下载应用的签名证书",
        "description": "下载应用的签名证书",
        "operationId": "downloadAppPublicKey",
        "security": [
          {
            "uc_auth": ["read:app_publickey"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/orgs": {
      "get": {
        "tags": ["Application"],
        "summary": "列出应用分配的组织结构树",
        "description": "列出应用分配的组织结构树",
        "operationId": "listEntitledOrgTree",
        "security": [
          {
            "uc_auth": ["list:org_apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/orgs/{org_id}": {
      "post": {
        "tags": ["Application"],
        "summary": "给单个组织结构分配应用",
        "description": "给单个组织结构分配应用",
        "operationId": "entitleOrg",
        "security": [
          {
            "uc_auth": ["update:org_apps"]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Application"],
        "summary": "从应用中已分配的组织结构列表中移除单个组织结构",
        "description": "从应用中已分配的组织结构列表中移除单个组织结构",
        "operationId": "revokeOrgEntitlement",
        "security": [
          {
            "uc_auth": ["update:org_apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/permission_sets": {
      "get": {
        "tags": ["Application Role"],
        "summary": "获取某个应用下的权限组列表",
        "description": "可以是获取某个应用下所有权限组列表，也可以通过对名称和描述进行搜索来获取满足条件的权限组列表（搜索的标准是字符串的匹配）",
        "operationId": "searchPermissionSets",
        "security": [
          {
            "uc_auth": ["search:permission_sets"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Application Role"],
        "summary": "为某个应用创建一个权限组",
        "description": "为某个应用创建一个权限组",
        "operationId": "createPermissionSet",
        "security": [
          {
            "uc_auth": ["create:permission_sets"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/permission_sets/{permission_set_name}": {
      "get": {
        "tags": ["Application Role"],
        "summary": "获取某个应用的某个权限组",
        "description": "获取某个应用的某个权限组",
        "operationId": "getPermissionSet",
        "security": [
          {
            "uc_auth": ["read:permission_sets"]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Application Role"],
        "summary": "删除某个应用的某个权限组",
        "description": "删除某个应用的某个权限组",
        "operationId": "deletePermissionSet",
        "security": [
          {
            "uc_auth": ["delete:permission_sets"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Application Role"],
        "summary": "更新某个应用的某个权限组",
        "description": "更新某个应用的某个权限组",
        "operationId": "updatePermissionSet",
        "security": [
          {
            "uc_auth": ["update:permission_sets"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/permissions": {
      "get": {
        "tags": ["Application Role"],
        "summary": "获取某个应用下的权限列表",
        "description": "可以是获取某个应用下所有权限列表，也可以通过对名称和描述进行搜索来获取满足条件的权限列表（搜索的标准是字符串的匹配）",
        "operationId": "searchPermissions",
        "security": [
          {
            "uc_auth": ["search:permissions"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Application Role"],
        "summary": "为某个应用创建一个权限",
        "description": "为某个应用创建一个权限",
        "operationId": "createPermission",
        "security": [
          {
            "uc_auth": ["create:permissions"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/permissions/{permission_name}": {
      "get": {
        "tags": ["Application Role"],
        "summary": "获取某个应用的某个权限",
        "description": "获取某个应用的某个权限",
        "operationId": "getName",
        "security": [
          {
            "uc_auth": ["read:permissions"]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Application Role"],
        "summary": "删除某个应用的某个权限",
        "description": "删除某个应用的某个权限",
        "operationId": "deletePermission",
        "security": [
          {
            "uc_auth": ["delete:permissions"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Application Role"],
        "summary": "更新某个应用的某个权限",
        "description": "更新某个应用的某个权限",
        "operationId": "updatePermission",
        "security": [
          {
            "uc_auth": ["update:permissions"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/public_access": {
      "put": {
        "tags": ["Application"],
        "summary": "更新应用的公开访问配置",
        "description": "更新应用的公开访问配置",
        "operationId": "updateAppPublicAccessUsingPUT",
        "security": [
          {
            "uc_auth": ["update:apps_public_access"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/publickey": {
      "get": {
        "tags": ["Application"],
        "summary": "获取应用的签名证书",
        "description": "获取应用的签名证书",
        "operationId": "getAppPublicKey",
        "security": [
          {
            "uc_auth": ["read:app_publickey"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/rbac/import": {
      "post": {
        "tags": ["Application Role Assignment"],
        "summary": "上传csv文件来导入用户和组织结构的角色绑定关系",
        "description": "上传csv文件来导入用户和组织结构的角色绑定关系。\n\r**Note:**\n\r1. 文件编码格式：下载的csv导入模板文件是UTF8编码的文件（带有BOM标志），在window平台可以用MS Excel或记事本（Notepad）打开。如果在Windows平台上用MS Excel编辑后再保存，文件将被ANSI编码（对于中文，实际的编码很可能是CP936）。当然你也可以用其他工具把ANSI编码文件转成UTF8编码文件。上传文件时，API同时支持UTF8和ANSI(CP936)编码格式。\n\r2. 文件内容格式：正确的内容格式要符合模板文件的要求，第一行是表头。\n\r3. 约束条件：角色绑定关系中用到的角色，用户和组织结构必须已经存在，否则将报错。\n\r4. 约束条件：用户中心(usercenter)只能与用户，不能与组织结构建立角色绑定关系。",
        "operationId": "createByCsv",
        "security": [
          {
            "uc_auth": ["import:role_bindings"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/role_permissions/import": {
      "post": {
        "tags": ["Application Role"],
        "summary": "上传csv文件来导入权限/权限组/角色",
        "description": "上传csv文件来导入权限/权限组/角色。\n\r**Note:**\n\r1. 文件编码格式：下载的csv导入模板文件是UTF8编码的文件（带有BOM标志），在window平台可以用MS Excel或记事本（Notepad）打开。如果在Windows平台上用MS Excel编辑后再保存，文件将被ANSI编码（对于中文，实际的编码很可能是CP936）。当然你也可以用其他工具把ANSI编码文件转成UTF8编码文件。上传文件时，API同时支持UTF8和ANSI(CP936)编码格式。\n\r2. 文件内容格式：正确的内容格式要符合模板文件的要求，第一行是表头。\n\r3. 约束条件：权限组的导入，如果指定了权限，则该权限必须先于权限组导入，否则将报错。角色的导入同理，如果指定了权限和权限组，则权限和权限组必须先于角色的导入，否则将报错。",
        "operationId": "createByCsv_1",
        "security": [
          {
            "uc_auth": ["import:permissions"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/roles": {
      "get": {
        "tags": ["Application Role"],
        "summary": "获取某个应用下的角色列表",
        "description": "可以是获取某个应用下所有角色列表，也可以通过对名称和描述进行搜索来获取满足条件的角色列表（搜索的标准是字符串的匹配）",
        "operationId": "searchRoles",
        "security": [
          {
            "uc_auth": ["search:roles"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Application Role"],
        "summary": "为某个应用创建一个角色",
        "description": "为某个应用创建一个角色",
        "operationId": "createRole",
        "security": [
          {
            "uc_auth": ["create:roles"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/roles/orgs": {
      "get": {
        "tags": ["Application Role Assignment"],
        "summary": "获取某个组织结构的角色绑定关系",
        "description": "获取某个组织结构的角色绑定关系",
        "operationId": "getOrgRoleBindings",
        "security": [
          {
            "uc_auth": ["list:org_roles"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/roles/tags": {
      "get": {
        "tags": ["Application Role Assignment"],
        "summary": "获取某个标签的角色绑定关系",
        "description": "获取某个标签的角色绑定关系",
        "operationId": "getTagRoleBindings",
        "security": [
          {
            "uc_auth": ["list:tag_roles"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/roles/users": {
      "get": {
        "tags": ["Application Role Assignment"],
        "summary": "获取某个用户的角色绑定关系",
        "description": "获取某个用户的角色绑定关系",
        "operationId": "getUserRoleBindings",
        "security": [
          {
            "uc_auth": ["list:user_roles"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/roles/{role_name}": {
      "get": {
        "tags": ["Application Role"],
        "summary": "获取某个应用的某个角色",
        "description": "获取某个应用的某个角色",
        "operationId": "getRole",
        "security": [
          {
            "uc_auth": ["read:roles"]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Application Role"],
        "summary": "删除某个应用的某个角色",
        "description": "删除某个应用的某个角色。系统内置的角色(createMode=BY_ADMIN)，无法删除",
        "operationId": "deleteRole",
        "security": [
          {
            "uc_auth": ["delete:roles"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Application Role"],
        "summary": "更新某个应用的某个角色",
        "description": "更新某个应用的某个角色。对于用户中心的系统内置(createMode=BY_SYSTEM)角色，仅可更新显示名和描述，不能更新permission_sets",
        "operationId": "updateRole",
        "security": [
          {
            "uc_auth": ["update:roles"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/roles/{role_name}/orgs": {
      "get": {
        "tags": ["Application Role Assignment"],
        "summary": "列出某个app下得某个角色已分配得组织结构列表",
        "description": "列出某个app下得某个角色已分配得组织结构列表",
        "operationId": "searchOrgs_1",
        "security": [
          {
            "uc_auth": ["list:org_roles"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Application Role Assignment"],
        "summary": "创建组织结构的角色绑定",
        "description": "创建组织结构的角色绑定",
        "operationId": "createOrgRoleBinding",
        "security": [
          {
            "uc_auth": ["update:org_roles"]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Application Role Assignment"],
        "summary": "删除组织结构的角色绑定",
        "description": "删除组织结构的角色绑定",
        "operationId": "deleteOrgRoleBindings",
        "security": [
          {
            "uc_auth": ["update:org_roles"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Application Role Assignment"],
        "summary": "更新组织结构的角色绑定",
        "description": "更新组织结构的角色绑定",
        "operationId": "updateOrgRoleBinding",
        "security": [
          {
            "uc_auth": ["update:org_roles"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/roles/{role_name}/tags": {
      "get": {
        "tags": ["Application Role Assignment"],
        "summary": "列出某个app下得某个角色已分配的标签列表",
        "description": "列出某个app下得某个角色已分配的标签列表",
        "operationId": "searchOrgs_2",
        "security": [
          {
            "uc_auth": ["list:tag_roles"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Application Role Assignment"],
        "summary": "创建标签的角色绑定",
        "description": "创建标签的角色绑定",
        "operationId": "createTagRoleBinding",
        "security": [
          {
            "uc_auth": ["update:tag_roles"]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Application Role Assignment"],
        "summary": "删除标签角色绑定",
        "description": "删除标签角色绑定",
        "operationId": "deleteTagRoleBindings",
        "security": [
          {
            "uc_auth": ["update:tag_roles"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Application Role Assignment"],
        "summary": "更新标签角色绑定",
        "description": "更新标签角色绑定",
        "operationId": "updateTagRoleBinding",
        "security": [
          {
            "uc_auth": ["update:tag_roles"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/roles/{role_name}/users": {
      "get": {
        "tags": ["Application Role Assignment"],
        "summary": "列出某个app下得某个角色已分配得用户列表",
        "description": "针对用户登录名，全名，电子邮件，移动电话号码，模糊查询用户。\n\r查询匹配的标准是字符串的子串匹配方式。\n\r**注意: 即使在查询参数'attrs'中指定了敏感信息（如密码），API也不会返回。**",
        "operationId": "searchUsers",
        "security": [
          {
            "uc_auth": ["list:user_roles"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Application Role Assignment"],
        "summary": "创建用户的角色绑定",
        "description": "创建用户的角色绑定",
        "operationId": "createUserRoleBinding",
        "security": [
          {
            "uc_auth": ["update:user_roles"]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Application Role Assignment"],
        "summary": "删除用户角色绑定",
        "description": "删除用户角色绑定",
        "operationId": "deleteUserRoleBindings",
        "security": [
          {
            "uc_auth": ["update:user_roles"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Application Role Assignment"],
        "summary": "更新用户角色绑定",
        "description": "更新用户角色绑定",
        "operationId": "updateUserRoleBinding",
        "security": [
          {
            "uc_auth": ["update:user_roles"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/secret": {
      "patch": {
        "tags": ["Application"],
        "summary": "重新生成新的client secret。只有cli,web类型的client才有secret，native/spa类型的没有secret。",
        "description": "新的client secret生成后,老的secret将无效，请在您的应用里使用更新后的secret",
        "operationId": "rotateClientSecret",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/signature_secret": {
      "patch": {
        "tags": ["Application"],
        "summary": "重新生成新的对称签名秘钥。",
        "description": "新的client signature secret生成后,老的secret将无效，请在您的应用里使用更新后的secret",
        "operationId": "rotateClientSignatureSecret",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/status": {
      "put": {
        "tags": ["Application"],
        "summary": "改变应用的状态",
        "description": "改变应用的状态。",
        "operationId": "changeAppStatus",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/tags": {
      "get": {
        "tags": ["Application"],
        "summary": "查看已经分配应用的标签列表",
        "description": "查看已经分配应用的标签列表，可针对标签名称，描述模糊查询标签。\n\r查询匹配的标准是字符串的子串匹配方式。",
        "operationId": "listEntitledUsers",
        "security": [
          {
            "uc_auth": ["list:tag_apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/tags/add": {
      "post": {
        "tags": ["Application"],
        "summary": "给多个标签分配应用",
        "description": "给多个标签分配应用",
        "operationId": "entitleTags",
        "security": [
          {
            "uc_auth": ["update:tag_apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/tags/remove": {
      "post": {
        "tags": ["Application"],
        "summary": "从应用中已分配的用户标签列表中移除标签",
        "description": "从应用中已分配的用户标签列表中移除标签",
        "operationId": "revokeTagsEntitlement",
        "security": [
          {
            "uc_auth": ["update:tag_apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/tenants": {
      "get": {
        "tags": ["Application"],
        "summary": "获取能使用该应用的租户列表",
        "description": "获取能使用该应用的租户列表",
        "operationId": "getAssignedTenantsUsingGET",
        "security": [
          {
            "uc_auth": ["read:apps"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Application"],
        "summary": "给单个组织结构分配应用",
        "description": "给单个组织结构分配应用",
        "operationId": "setAssignedTenants",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/user": {
      "post": {
        "tags": ["Application"],
        "summary": "给单个用户分配应用",
        "description": "给单个用户分配应用",
        "operationId": "entitleUser",
        "security": [
          {
            "uc_auth": ["update:user_apps"]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Application"],
        "summary": "从应用中已分配的用户列表中移除单个用户",
        "description": "从应用中已分配的用户列表中移除单个用户",
        "operationId": "revokeUserEntitlement",
        "security": [
          {
            "uc_auth": ["update:user_apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/users": {
      "get": {
        "tags": ["Application"],
        "summary": "查看已经分配应用的用户列表",
        "description": "查看已经分配应用的用户列表，可针对用户登录名，全名，电子邮件，移动电话号码和状态属性，模糊查询用户。\n\r查询匹配的标准是字符串的子串匹配方式。\n\r**如果查询参数'q'没有指定，即使指定了返回用户列表的排序方式，API也会使用缺省的'username asc, name asc, email asc'来排序。** \n\r**注意: 即使在查询参数'attrs'中指定了敏感信息（如密码），API也不会返回。**",
        "operationId": "listEntitledUsers_1",
        "security": [
          {
            "uc_auth": ["list:user_apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/users/add": {
      "post": {
        "tags": ["Application"],
        "summary": "给多个用户分配应用",
        "description": "给多个用户分配应用",
        "operationId": "entitleUsers",
        "security": [
          {
            "uc_auth": ["update:user_apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/users/remove": {
      "post": {
        "tags": ["Application"],
        "summary": "从应用中已分配的用户列表中移除用户",
        "description": "从应用中已分配的用户列表中移除用户",
        "operationId": "revokeUsersEntitlement",
        "security": [
          {
            "uc_auth": ["update:user_apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/apps/{client_id}/whitelisted": {
      "put": {
        "tags": ["Application"],
        "summary": "设置应用是否加入或退出授权白名单",
        "description": "设置应用是否加入或退出授权白名单",
        "operationId": "changeWhitelisted",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/auditlog": {
      "get": {
        "tags": ["Auditlog"],
        "summary": "查询审计日志",
        "description": "查询审计日志",
        "operationId": "searchAuditlog",
        "security": [
          {
            "uc_auth": ["search:auditlog"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/auditlog/export": {
      "get": {
        "tags": ["Auditlog"],
        "summary": "获取登录日志",
        "description": "获取登录日志",
        "operationId": "exportAuditlog",
        "security": [
          {
            "uc_auth": []
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/auth_factors": {
      "get": {
        "tags": ["Auth Factor"],
        "summary": "获取认证因子列表",
        "description": "获取认证因子列表",
        "operationId": "listAuthFactors",
        "security": [
          {
            "uc_auth": ["search:auth_factors"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/auth_factors/update": {
      "post": {
        "tags": ["Auth Factor"],
        "summary": "更新认证因子",
        "description": "更新认证因子",
        "operationId": "updateAuthFactor_1",
        "security": [
          {
            "uc_auth": ["update:auth_factors"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Auth Factor"],
        "summary": "更新认证因子",
        "description": "更新认证因子",
        "operationId": "updateAuthFactor",
        "security": [
          {
            "uc_auth": ["update:auth_factors"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/auth_factors/{auth_method}": {
      "get": {
        "tags": ["Auth Factor"],
        "summary": "获取某个认证因子详情",
        "description": "获取某个认证因子详情",
        "operationId": "getAuthFactor",
        "security": [
          {
            "uc_auth": ["read:auth_factors"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/auth_factors/{auth_method}/status": {
      "post": {
        "tags": ["Auth Factor"],
        "summary": "更新认证因子状态",
        "description": "更新认证因子状态",
        "operationId": "changeAuthFactorStatus",
        "security": [
          {
            "uc_auth": ["update:auth_factors"]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": ["Auth Factor"],
        "summary": "更新认证因子状态",
        "description": "更新认证因子状态",
        "operationId": "changeAuthFactorStatus_1",
        "security": [
          {
            "uc_auth": ["update:auth_factors"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Auth Factor"],
        "summary": "更新认证因子状态",
        "description": "更新认证因子状态",
        "operationId": "changeAuthFactorStatus_2",
        "security": [
          {
            "uc_auth": ["update:auth_factors"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/auth/{auth_id}": {
      "get": {
        "tags": ["Configs"],
        "summary": "getAuthProviderConfig",
        "operationId": "getAuthProviderConfigUsingGET",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/email": {
      "get": {
        "tags": ["Configs"],
        "summary": "获取电子邮件配置信息",
        "description": "获取电子邮件配置信息",
        "operationId": "getEmailConfig",
        "security": [
          {
            "uc_auth": ["read:email_configs"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Configs"],
        "summary": "更新电子邮件配置信息",
        "description": "更新电子邮件配置信息",
        "operationId": "updateEmailConfigs",
        "security": [
          {
            "uc_auth": ["update:email_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/policies": {
      "get": {
        "tags": ["Configs"],
        "summary": "获取策略配置信息",
        "description": "获取策略配置信息",
        "operationId": "getPoliciesConfig",
        "security": [
          {
            "uc_auth": []
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Configs"],
        "summary": "更新策略配置信息",
        "description": "更新策略配置信息",
        "operationId": "updatePoliciesConfigs",
        "security": [
          {
            "uc_auth": ["update:policies_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/providers/baseInfo": {
      "get": {
        "tags": ["Configs"],
        "summary": "获取企业认证源基础信息列表",
        "description": "获取企业认证源基础信息列表",
        "operationId": "Get all auth provider list ",
        "security": [
          {
            "uc_auth": ["read:sns_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/sms": {
      "get": {
        "tags": ["Configs"],
        "summary": "获取短信网关配置信息",
        "description": "获取短信网关配置信息",
        "operationId": "getSmsConfig",
        "security": [
          {
            "uc_auth": ["read:sms_configs"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Configs"],
        "summary": "更新短信网关配置信息",
        "description": "更新短信网关配置信息",
        "operationId": "updateSmsConfig",
        "security": [
          {
            "uc_auth": ["update:sms_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/sns": {
      "get": {
        "tags": ["Configs"],
        "summary": "获取企业第三方平台配置信息列表，分页",
        "description": "获取企业第三方平台配置信息列表，分页",
        "operationId": "Get sns config list ",
        "security": [
          {
            "uc_auth": ["read:sns_configs"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Configs"],
        "summary": "创建企业第三方平台配置",
        "description": "创建企业第三方平台配置",
        "operationId": "create sns Config",
        "security": [
          {
            "uc_auth": ["update:sns_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/sns/default": {
      "post": {
        "tags": ["Configs"],
        "summary": "设置企业第三方平台默认配置",
        "description": "设置企业第三方平台默认配置",
        "operationId": "set sns default Config",
        "security": [
          {
            "uc_auth": ["update:sns_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/sns/delete": {
      "post": {
        "tags": ["Configs"],
        "summary": "删除企业第三方平台配置",
        "description": "删除企业第三方平台配置",
        "operationId": "delete sns Config",
        "security": [
          {
            "uc_auth": ["update:sns_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/sns/get_all": {
      "get": {
        "tags": ["Configs"],
        "summary": "获取企业第三方平台配置信息列表",
        "description": "获取企业第三方平台配置信息列表",
        "operationId": "Get all sns config list ",
        "security": [
          {
            "uc_auth": ["read:sns_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/sns/status/{id}/{status}": {
      "put": {
        "tags": ["Configs"],
        "summary": "启用/禁用企业第三方平台配置",
        "description": "启用/禁用企业第三方平台配置",
        "operationId": "change sns Config status",
        "security": [
          {
            "uc_auth": ["update:sns_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/sns/{id}": {
      "get": {
        "tags": ["Configs"],
        "summary": "获取指定企业第三方平台配置",
        "description": "获取指定企业第三方平台配置",
        "operationId": "Get sns configs",
        "security": [
          {
            "uc_auth": ["read:sns_configs"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Configs"],
        "summary": "修改企业第三方平台配置",
        "description": "修改企业第三方平台配置",
        "operationId": "modify sns Config",
        "security": [
          {
            "uc_auth": ["update:sns_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/configs/sns/{type}": {
      "get": {
        "tags": ["Configs"],
        "summary": "根据类型获取企业第三方平台配置信息列表",
        "description": "根据类型获取企业第三方平台配置信息列表",
        "operationId": "Get all sns config list  by type ",
        "security": [
          {
            "uc_auth": ["read:sns_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connect/ding/approveApp/{clientId}/{userId}": {
      "post": {
        "tags": ["ConnectDing"],
        "summary": "approveAuthApp",
        "operationId": "approveAuthAppUsingPOST",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connect/ding/listApps": {
      "get": {
        "tags": ["ConnectDing"],
        "summary": "应用列表",
        "description": "应用列表",
        "operationId": "listApps",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connect/ding/test": {
      "get": {
        "tags": ["ConnectDing"],
        "summary": "testConnectorByGet",
        "operationId": "testConnectorByGetUsingGET",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["ConnectDing"],
        "summary": "testConnectorByPost",
        "operationId": "testConnectorByPostUsingPOST",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors": {
      "get": {
        "tags": ["Connector"],
        "summary": "获取所有链接器的配置信息",
        "description": "获取所有链接器的配置信息",
        "operationId": "Get all connector config profiles",
        "security": [
          {
            "uc_auth": ["read:datasource_configs"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Connector"],
        "summary": "创建链接器",
        "description": "创建链接器",
        "operationId": "Create connector",
        "security": [
          {
            "uc_auth": ["create:datasource_configs"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Connector"],
        "summary": "更新指定链接器的配置信息",
        "description": "更新指定链接器的配置信息",
        "operationId": "Update specified connector config profiles",
        "security": [
          {
            "uc_auth": ["update:datasource_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors/auth_configs": {
      "get": {
        "tags": ["Connector"],
        "summary": "获取租户所有链接器的登录认证配置",
        "description": "获取租户所有链接器的登录认证配置",
        "operationId": "Get all connector auth config",
        "security": [
          {
            "uc_auth": ["read:datasource_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors/change_status": {
      "post": {
        "tags": ["Connector"],
        "summary": "修改连接器状态",
        "description": "修改连接器状态",
        "operationId": "修改连接器状态_1",
        "security": [
          {
            "uc_auth": ["update:datasource_configs"]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": ["Connector"],
        "summary": "修改连接器状态",
        "description": "修改连接器状态",
        "operationId": "修改连接器状态",
        "security": [
          {
            "uc_auth": ["update:datasource_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors/deleteLimitPushUsers": {
      "get": {
        "tags": ["Connector"],
        "summary": "查询推送数据时移除的记录",
        "description": "查询推送数据时移除的记录",
        "operationId": "查询推送数据时移除的记录",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors/deleteLimitSyncUsers": {
      "get": {
        "tags": ["Connector"],
        "summary": "查询同步数据时移除的记录",
        "description": "查询同步数据时移除的记录",
        "operationId": "查询同步数据时移除的记录",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors/getAuthConfig": {
      "get": {
        "tags": ["Connector"],
        "summary": "获取租户链接器的登录认证配置",
        "description": "获取租户链接器的登录认证配置",
        "operationId": "Get connector auth config",
        "security": [
          {
            "uc_auth": ["read:datasource_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors/pre_import/config": {
      "get": {
        "tags": ["Connector"],
        "summary": "获取导入配置信息",
        "description": "上一次设置的导入配置信息",
        "operationId": "get pre-import config",
        "security": [
          {
            "uc_auth": ["read:idp_pre_import_config"]
          }
        ],
        "deprecated": false
      },
      "patch": {
        "tags": ["Connector"],
        "summary": "修改导入配置信息",
        "description": "修改上一次设置的导入配置信息",
        "operationId": "Update pre-import config",
        "security": [
          {
            "uc_auth": ["update:idp_pre_import_config"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors/pre_import/config/tips": {
      "get": {
        "tags": ["Connector"],
        "summary": "获取导入配置输入提示信息",
        "description": "AD/LDAP导入与同步配置提示信息，返回包含AD和LDAP填写项提示信息数组，数组元素的返回结构与 GET：/pre_import/config的返回结构相同",
        "operationId": "get pre-import config tips",
        "security": [
          {
            "uc_auth": ["read:idp_pre_import_config_tips"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors/sync_test": {
      "post": {
        "tags": ["Connector"],
        "summary": "显示指定的用户信息",
        "description": "输入用户标示，显示指定的用户信息.文档的成功返回信息中，缺少了group字段。",
        "operationId": "Show user info from sync profile",
        "security": [
          {
            "uc_auth": ["test:datasource_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors/{profileName}": {
      "get": {
        "tags": ["Connector"],
        "summary": "获取指定链接器的配置信息",
        "description": "获取指定链接器的配置信息",
        "operationId": "Get specified connector config profiles",
        "security": [
          {
            "uc_auth": ["read:datasource_configs"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/connectors/{profileName}/sync_now": {
      "post": {
        "tags": ["Connector"],
        "summary": "手动从链接器同步用户信息",
        "description": "手动从链接器同步用户信息",
        "operationId": "connector manual sync user",
        "security": [
          {
            "uc_auth": ["sync:datasource"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/createConversation/{name}": {
      "post": {
        "tags": ["User Conversation"],
        "summary": "根据标签创建群聊",
        "description": "根据标签创建群聊",
        "operationId": "createConversation",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/createTagAndAddUsers": {
      "post": {
        "tags": ["User Tag"],
        "summary": "创建标签并且添加用户",
        "description": "创建标签并且添加用户",
        "operationId": "createTagAndAddUsers",
        "security": [
          {
            "uc_auth": ["update:user_tags"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/dingaudit": {
      "post": {
        "tags": ["Audit"],
        "summary": "查询钉钉审计日志",
        "description": "查询钉钉审计日志",
        "operationId": "searchDingAudit_1",
        "security": [
          {
            "uc_auth": ["search:auditlog"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/dingaudit/export": {
      "get": {
        "tags": ["Audit"],
        "summary": "导出钉钉审计日志",
        "description": "导出钉钉审计日志",
        "operationId": "exportDingAudit",
        "security": [
          {
            "uc_auth": ["search:auditlog"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/dingaudit/info": {
      "get": {
        "tags": ["Audit"],
        "summary": "查询钉钉审计日志明细",
        "description": "查询钉钉审计日志明细",
        "operationId": "searchDingAudit",
        "security": [
          {
            "uc_auth": ["search:auditlog"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/email": {
      "post": {
        "tags": ["Email"],
        "summary": "发送电子邮件",
        "description": "发送电子邮件",
        "operationId": "send email",
        "security": [
          {
            "uc_auth": ["send:email"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/flows": {
      "get": {
        "tags": ["Links"],
        "summary": "查询连接流列表",
        "description": "查询连接流列表",
        "operationId": "queryFlowsUsingGET",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Links"],
        "summary": "创建连接流",
        "description": "创建连接流",
        "operationId": "createFlowUsingPOST",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/flows/{id}": {
      "get": {
        "tags": ["Links"],
        "summary": "获取连接流详情",
        "description": "获取连接流详情",
        "operationId": "getFlowUsingGET",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": ["Links"],
        "summary": "替换修改连接流",
        "description": "替换修改连接流",
        "operationId": "replaceFlowUsingPUT",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": ["Links"],
        "summary": "删除连接流",
        "description": "删除连接流",
        "operationId": "deleteFlowUsingDELETE",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/gateway": {
      "get": {
        "tags": ["Gateway Application"],
        "summary": "加载应用网关",
        "description": "加载应用网关",
        "operationId": "loadGateWay",
        "security": [
          {
            "uc_auth": ["read:apps"]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": ["Gateway Application"],
        "summary": "保存应用网关",
        "description": "保存应用网关",
        "operationId": "saveGateWay",
        "security": [
          {
            "uc_auth": ["update:apps"]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/apps/{client_id}": {
      "get": {
        "tags": ["Inner Api"],
        "summary": "获取应用详细信息",
        "description": "获取应用详细信息",
        "operationId": "getAppDetails_2",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/auditLog": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "recordAuditLog",
        "operationId": "recordAuditLogUsingPOST",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/etl_sync/{datasource_id}": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "通知链接器同步用户信息",
        "description": "通知链接器同步用户信息",
        "operationId": "notify connector to sync user",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/otp/send_otp": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "sendOtp",
        "operationId": "sendOtpUsingPOST",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/otp/verify": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "otpVerify",
        "operationId": "otpVerifyUsingPOST",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/sns": {
      "get": {
        "tags": ["Inner Api"],
        "summary": "获取企业第三方平台配置信息列表",
        "description": "获取企业第三方平台配置信息列表",
        "operationId": "Get all sns corp info config list ",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/sns/{id}": {
      "get": {
        "tags": ["Inner Api"],
        "summary": "获取企业第三方平台配置信息",
        "description": "获取企业第三方平台配置信息列表",
        "operationId": "get sns config ",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/users/getOrgBasicInfoByOrgIds": {
      "get": {
        "tags": ["Inner Api"],
        "summary": "根据IAM组ID获取组基本信息",
        "description": "根据IAM组ID获取组基本信息",
        "operationId": "get org basic info by org ids",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/users/getOrgIdsBySnsGroupCodes": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "根据第三方平台组代码获取iam组ID列表",
        "description": "根据第三方平台组代码获取iam组ID列表",
        "operationId": "get iam org id by sns group code",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/users/getSnsGroupCodesByOrgIds": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "根据iam组ID获取第三方平台组代码列表",
        "description": "根据iam组ID获取第三方平台组代码列表",
        "operationId": "get sns group code by iam org id ",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/users/getSnsUnionIdsByUserIds": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "根据iam用户ID获取第三方平台用户ID列表",
        "description": "根据iam用户ID获取第三方平台用户 union id 列表",
        "operationId": "get sns union id by iam user id ",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/users/getSnsUserIdsByUserIds": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "根据iam用户ID获取第三方平台用户ID列表",
        "description": "根据iam用户ID获取第三方平台用户ID列表",
        "operationId": "get sns user id by iam user id ",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/users/getUserBasicInfoByUserIds": {
      "get": {
        "tags": ["Inner Api"],
        "summary": "根据IAM用户ID获取用户基本信息",
        "description": "根据IAM用户ID获取用户基本信息",
        "operationId": "get user basic info by user ids",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/users/getUserIdsByOrgIds": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "根据iam用户组ID获取用户ID列表",
        "description": "根据iam用户组ID获取用户ID列表",
        "operationId": "get user id by org id list",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/users/getUserIdsBySnsUserIds": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "根据第三方平台用户ID获取iam用户ID列表",
        "description": "根据第三方平台用户ID获取iam用户ID列表",
        "operationId": "get iam user id by sns user id ",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
              "delete:tags",
              "read:templates",
              "update:templates",
              "search:auditlog",
              "create:permissions",
              "search:permissions",
              "read:permissions",
              "update:permissions",
              "delete:permissions",
              "create:permission_sets",
              "search:permission_sets",
              "read:permission_sets",
              "update:permission_sets",
              "delete:permission_sets",
              "create:roles",
              "search:roles",
              "read:roles",
              "update:roles",
              "delete:roles",
              "update:user_roles",
              "update:org_roles",
              "list:org_roles",
              "list:user_roles",
              "update:tag_roles",
              "list:tag_roles",
              "create:profiles",
              "read:profiles",
              "search:profiles",
              "update:profiles",
              "delete:profiles"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/iam/api/inner/users/getUserIdsByUserCodes": {
      "post": {
        "tags": ["Inner Api"],
        "summary": "根据iam用户编号获取iam用户ID列表",
        "description": "根据iam用户编号获取用户ID列表",
        "operationId": "get user id by iam user code ",
        "security": [
          {
            "uc_auth": [
              "create:organizations",
              "update:organizations",
              "read:organizations",
              "search:organizations",
              "no_scope_search:organizations",
              "delete:organizations",
              "create:users",
              "read:user_full_info",
              "search:users",
              "no_scope_search:users",
              "update:users",
              "delete:users",
              "move_org:users",
              "export:users",
              "import:users",
              "update:users_pwd_by_admin",
              "create:user_attrs",
              "read:user_attr_all",
              "read:user_attrs",
              "update:user_attrs",
              "read:tokens",
              "delete:tokens",
              "create:reset_pwd_tokens",
              "create:email_tokens",
              "read:self_info",
              "read:self_application",
              "update:self_info",
              "delete:self_auth",
              "send_email_to_verify:self_info",
              "logout:self",
              "verify_mobile_code:self_info",
              "send_verify_mobile_code:self_info",
              "update:policies_configs",
              "read:email_configs",
              "update:email_configs",
              "read:idp_pre_import_config",
              "read:idp_pre_import_config_tips",
              "update:idp_pre_import_config",
              "read:sms_configs",
              "update:sms_configs",
              "create:datasource_configs",
              "update:datasource_configs",
              "read:datasource_configs",
              "delete:datasource_configs",
              "sync:datasource",
              "test:datasource_configs",
              "read:csv_import_status",
              "send:email",
              "create:apps",
              "search:apps",
              "read:apps",
              "update:apps",
              "delete:apps",
              "update:user_apps",
              "update:org_apps",
              "list:user_apps",
              "list:org_apps",
              "update:tag_apps",
              "list:tag_apps",
              "update:apps_public_access",
              "create:tags",
              "search:tags",
              "read:tags",
              "update:tags",
[...]
